### PR TITLE
Added `CAN_LOGIN_AS_USER_IDS` & `CAN_LOGIN_AS_USER_EMAILS` settings.

### PR DESCRIPTION
**Pull request by caxap**

### CODE REVIEW

**Comment by skorokithakis** [comment]
Thank you! Can you explain the motivation behind this a bit? Why do these two options need to be in loginas, rather than being implemented by the user using the custom `CAN_LOGIN_AS` function?

**Comment by caxap** [comment]
I guess that the pretty most cases to override `CAN_LOGIN_AS ` is allow your team members login as some user. And there are two ways to do that, define list of ids or define  list of emails. So it nice to have just setting to do that.

**Comment by skorokithakis** [comment]
Yeah, but since we already have a pretty easy way of doing that (with the custom function), I'm not sure it would be very beneficial to add code to do that by default... I wonder if we can add this code as an example somewhere, though.

**Comment by caxap** [comment]
@skorokithakis sorry for delay, off course it's up to you.

**Comment by skorokithakis** [comment]
No problem! Yeah, I think it would be better if it were an example of how to write your own function to check emails/usernames. I'll add it to the docs, if you don't get to it first, thanks for your time!

**Pull request closed without merging**
