### PR TITLE
FIX : Rm user session flag

### PR DESCRIPTION
**Pull request by palmitoto**
I do not really understand cause the behavior is random. Sometimes the key disappears sometimes not ... I did a pull request, tell me what you think about it.

### CODE REVIEW

**Comment by palmitoto** [comment]
I do not really understand cause the behavior is random. Sometimes the key disappears sometimes not ... I did a pull request, tell me what you think about it.

**Comment by skorokithakis** [comment]
I'm guessing that `logout` deletes everything in the session, although I don't know why it doesn't with yours. Instead of catching *all* `KeyError`s, I would prefer if you did:

```
if la_settings.USER_SESSION_FLAG in request.session:
    del request.session[la_settings.USER_SESSION_FLAG]
```

That way, you aren't silencing errors that may happen in the other lines.

**Comment by skorokithakis** [comment]
Looks great, is it working well on your local setup?

**Comment by palmitoto** [comment]
I can not explain it, but better than yours 👍  ^^

**Comment by skorokithakis** [comment]
Merged, thank you!

**Pull request merged**
