### PR TITLE
Customizable Redirect URL

### PR DESCRIPTION
**Pull request by jarcoal**
Allow the redirect URL to be customized instead of just redirecting to /.

### CODE REVIEW

**Comment by skorokithakis** [comment]
Looks great, can you add a mention in the README as well? Then I can merge it.

**Comment by jarcoal** [comment]
Done!

**Comment by skorokithakis** [comment]
Looks great, thank you!

**Comment by jarcoal** [comment]
My pleasure.  It would be great if a release could be cut in the near future.

**Comment by skorokithakis** [comment]
Yep. I need to set up this repo to use semantic-release so I can cut releases with one command, but that takes time...

**Comment by skorokithakis** [comment]
And of course, PyPI is crashing...

**Pull request merged**
